### ISSUE TITLE
IOS Support?

### ISSUE THREAD

**Issue by rijine** [jgithaiga/nativescript-sms-inbox#1]

**Comment by rijine** [comment]
Plugin failed to read sms in IOS

**Comment by rijine** [comment]
@jgithaiga is it supports IOS?

**Comment by jgithaiga** [comment]
No, the plugin does not support iOS.

**Comment by rijine** [comment]
@jgithaiga can we enhance this to support IOS also?

**Comment by jgithaiga** [comment]
You are welcome to do that but the last time i checked, iOS did not allow access to device's 'inbox' (unless it is a jailbroken device).

**Comment by rijine** [comment]
@jgithaiga then we can't do anything. closing this issue.
Thanks.
