### ISSUE TITLE
How to get sent messages as well?

### ISSUE THREAD

**Issue by Omi231** [jgithaiga/nativescript-sms-inbox#3]
Hi, thanks for this amazing plugin.

I am making an sms app similar to an instant chat app. I tried to use this plugin but it only returns received messages. Is there any way i can get sent messages as well?

**Comment by jgithaiga** [comment]
Hi, 
This plugin does not support what you are asking for.
However you can use an "sms on sent/delivered" broadcast receiver to get the sent sms payload and save that to a db.
All the best.

**Comment by Omi231** [comment]
Thank you so much. Can you also suggest how to get call-history or call log? I found only one plugin which is outdated and no more working :(

**Comment by hamid09430** [comment]
ADD THIS FUNCTION IN nativescript-sms-inbox/index.android.js file


exports.getSMSWhere = function (filter, options) {
    var max = options.max || constants.READ_ALL_SMS,
            sort = options.sort || constants.DEFAULT_SORT_PROP,
            order = options.order || constants.DEFAULT_SORT_ORDER;
    return new Promise(function (resolve, reject) {
        var contentResolver = app.android.context.getContentResolver();
        var sortOrder = sort + " " + order + ((max == constants.READ_ALL_SMS) ? "" : " limit " + max);
        var columns = ["_id", "thread_id", "address", "date", "date_sent", "body", "type"];
        var cursor = contentResolver.query(android.net.Uri.parse(constants.CONTENT_SMS_URI),
                columns, filter, null, sortOrder);
        var count = cursor.getCount();

        var smsList = [];
        if (count > 0) {
            while (cursor.moveToNext()) {
                var smsModel = new Sms();
                smsModel.parseFromNative(cursor);
                smsList.push(smsModel);
            }
            cursor.close();
            resolve({data: smsList, total: count, status: "success"});
        } else {
            cursor.close();
            resolve({data: smsList, total: count, status: "success"});
        }

    });
};


then call it 
this will return all sent and received sms
