### ISSUE TITLE
TypeError: Cannot read property 'getContentResolver' of undefined

### ISSUE THREAD

**Issue by stefanthurnherr** [jgithaiga/nativescript-sms-inbox#4]
I'm getting the error above when trying to read sms from all/any inbox.

I'm using nativescript playground app to test my angular/nativescript application using the plugin, but very unlikely that it has something to do with the playground app since other plugins work fine.

Any ideas? Maybe an API that has changed in Android (I'm using Android 9)?

**Comment by stefanthurnherr** [comment]
@jgithaiga I created a pull request with a workaround that works for me - what do you think?

Documentation for the utils package used to fetch the reference to application context: https://docs.nativescript.org/api-reference/modules/_utils_utils_.ad

**Comment by jgithaiga** [comment]
@stefanthurnherr Thanks for this solution.

**Comment by stefanthurnherr** [comment]
@jgithaiga any release planned with this fix included?
