### ISSUE TITLE
nativescript_sms_inbox.aar

### ISSUE THREAD

**Issue by webleaf** [jgithaiga/nativescript-sms-inbox#6]
First of all. Thank you for plugin. It' useful and saves time a little bit)

Question is: npm module contain `nativescript_sms_inbox.aar` file, but where is Java source code of it? Does we really need Java part in this plugin?

**Comment by jgithaiga** [comment]
This plugin does not include any Java code.

**Comment by webleaf** [comment]
If there is no Java code, then there are should not be such file in npm module (it's redundant and suspiciously):
`node_modules/nativescript-sms-inbox/platforms/android/nativescript_sms_inbox.aar`
May be this file is generated because of `include.gradle` exist. Then maybe `include.gradle` should be removed for that.

**Comment by webleaf** [comment]
It seems that this file appears there only after build.

**Comment by jgithaiga** [comment]
Thank you for the pull request. I have published version 2.1.0.
